name: EpicDuels
version: 0.2.2
main: dev.epicduels.EpicDuels
api-version: '1.21'
load: STARTUP
generators:
  EpicDuels:
    dev.epicduels.world.VoidWorldGenerator
commands:
  duel:
    description: Main duel command
    aliases: [d]
permissions:
  epicduels.admin:
    default: op
  epicduels.duel:
    default: true
  epicduels.stats:
    default: true
