name: EpicDuels
version: 2.0.0
main: dev.epicduels.EpicDuels
description: 1v1 duels, team duels, tournaments and matchmaking
author: nuroso000
website: https://github.com/nuroso000/EpicDuels
api-version: '1.21'
load: STARTUP
generators:
  EpicDuels:
    dev.epicduels.world.VoidWorldGenerator
commands:
  duel:
    description: Main duel command
    usage: /<command> [menu|duels|matchmaking|stats|challenge|accept|deny|cancel|queue|spectate|forfeit|rematch|toggle|leaderboard|arena|kit|setlobby|lobby|reload]
    aliases: [d]
  party:
    description: Manage your party
    usage: /<command> [create|invite|accept|deny|leave|disband|list|start]
    aliases: [p]
permissions:
  epicduels.admin:
    default: op
  epicduels.duel:
    default: true
  epicduels.stats:
    default: true
  epicduels.party:
    default: true
  epicduels.spectate:
    default: true
