name: EpicDuels
version: 2.0.0
main: dev.epicduels.EpicDuels
api-version: '1.21'
load: STARTUP
generators:
  EpicDuels:
    dev.epicduels.world.VoidWorldGenerator
commands:
  duel:
    description: Main duel command
    aliases: [d]
  party:
    description: Manage your party
    aliases: [p]
permissions:
  epicduels.admin:
    default: op
  epicduels.duel:
    default: true
  epicduels.stats:
    default: true
  epicduels.party:
    default: true
